namespace CivicVoice
{
    internal static class NewspaperContent
    {
        // ── Shop name pools ───────────────────────────────────────────────
        // Each pool is used by a matching DoMake*Name() method in CivicVoiceSystem.
        // Placeholders: {shop} {cafe} {restaurant} {salon} {hardware} {deli} {gym} {company}

        public static readonly string[] ShopNames = {
            "Fresco", "Costmore", "Bullseye", "Oldi", "Webb's",
            "Pemberton's", "Hartley's", "The Cooperative", "ValueKing", "Bigl",
        };

        public static readonly string[] CafeNames = {
            "The Daily Grind", "Beanstalk", "Not Bad Coffee", "Grounds & Co.",
            "The Mug & Spoon", "Perky's", "Brew Brothers", "The Slow Pour", "Filter", "Two Sugars",
        };

        public static readonly string[] RestaurantNames = {
            "The Golden Fork", "Pasta Roma", "The Hungry Fox", "Ember & Salt",
            "The Ploughman's", "Noodle & Co.", "The Rusty Spoon", "Brick Lane Diner", "The Admiral", "Fork & Flame",
        };

        public static readonly string[] SalonNames = {
            "Curl Up & Dye", "The Mane Event", "Snip & Sip", "Fringe Benefits",
            "Clips", "Headlines", "The Cutting Room", "Shear Bliss", "Top Knot", "Trim & Proper",
        };

        public static readonly string[] HardwareNames = {
            "Bolt & Beam", "Granger's", "The Tool Shed", "Fix & Finish",
            "Hardwick's", "Iron & Oak", "Nuts & Bolts", "The Workshop", "Build Right", "Hammerhead",
        };

        public static readonly string[] DeliNames = {
            "The Good Slice", "Olive & Vine", "The Wedge", "Fork & Larder",
            "Cured", "The Counter", "Saltbox", "Grain & Grove", "Provisions", "The Pickle Jar",
        };

        public static readonly string[] GymNames = {
            "IronCore", "PeakFit", "The Sweat Shop", "Gainsville",
            "Flex & Flow", "The Grind", "PulseGym", "Strong & Co.", "BodyWorks", "The Pit",
        };

        // ── Company name word banks ───────────────────────────────────────
        // Used by DoMakeCompanyName() — corporate/investment-firm flavour.
        public static readonly string[] CompanyPrefixes = {
            "Continental", "Apex", "Caldwell", "Keystone", "Sterling",
            "Horizon", "Vanguard", "Cornerstone", "Frontier", "Summit", "Green", "Ashworth", "Western"
        };

        public static readonly string[] CompanySuffixes = {
            "Holdings", "Ventures", "Group", "Capital", "Partners", "Enterprises", "Industries", "& Associates", "Consulting"
        };

        // ── Teaser pool ───────────────────────────────────────────────────
        // Format: "Category: title | sub"
        // Title max ~20 chars, sub max ~30 chars.
        // Picked randomly by C#, parsed into tag/title/sub by TSX sidebar.
        public static readonly string[] TeaserPool = {
            // ── Weather ───────────────────────────────────────────────────
            "Weather: Light winds, mild | Good day to ignore your emails",
            "Weather: Overcast by noon | Sun briefly considered showing up",
            "Weather: Cold and still | Ideal conditions for not going out",
            "Weather: Rain by evening | Denied by everyone who left washing out",
            "Weather: Thick cloud cover | Silver lining: technically present",
            "Weather: Dry but grey | Council describes it as fine",
            "Weather: Strong winds due | Bins pre-emptively moved inside",
            "Weather: Frost overnight | Confirmed by everyone's car this morning",
            "Weather: Warm for the season | Nobody trusts it",
            "Weather: Drizzle until noon | Afternoon: more drizzle probably",
            "Weather: Gusts up to 40mph | Hats advised to stay home",
            "Weather: Sunny intervals | Intervals: brief and non-committal",
            "Weather: Temperatures drop | Residents locate winter coats",
            "Weather: Dense fog warning | Ignored by most, regretted by some",
            "Weather: Mostly dry today | Mostly, say forecasters carefully",
            "Weather: Sleet expected | Salt trucks briefed and ready",
            "Weather: Bright but cold | Misleading, say residents",
            "Weather: Humid all day | Windows: condensed, tempers: also",
            "Weather: Zero degrees tonight | Car scrapers: back in circulation",
            "Weather: Changeable outlook | As always, bring a coat anyway",
            // ── Letters ───────────────────────────────────────────────────
            "Letters: The new roundabout | Wrong in ways hard to explain",
            "Letters: Parking on my road | Not a car park, I have checked",
            "Letters: Speed bumps too high | Car: briefly airborne, now fine",
            "Letters: Library opening hours | Closed when I need it, open when I don't",
            "Letters: The new crossing | Button does nothing, I have timed it",
            "Letters: Noise from the park | Enjoyment: excessive and audible",
            "Letters: Planning permission | Approved for what exactly?",
            "Letters: The council website | Logged in once, never again",
            "Letters: Overgrown hedges | Visibility: gone, complaints: ongoing",
            "Letters: The post office queue | Worse since Tuesday, cause unknown",
            "Letters: Pavement outside mine | Cracked since 2021, still cracked",
            "Letters: New café prices | Charged for oat milk I did not request",
            "Letters: Dog walkers in general | Some of them, not all, but some",
            "Letters: The town newsletter | Arrived late, said nothing useful",
            "Letters: Litter near the school | Situation worsening, nobody surprised",
            "Letters: The leisure centre | Pool closed again, no reason given",
            "Letters: Bus stop missing | Removed. Bus still stops. Sign: gone.",
            "Letters: New street furniture | Nobody asked for this bench shape",
            "Letters: Fireworks last Tuesday | Not a weekend, not a holiday",
            "Letters: The car park barriers | Both of them, broken, again, still",
            // ── Horoscope ─────────────────────────────────────────────────
            "Horoscope: Trust your instincts | Except about the parking",
            "Horoscope: A delay is coming | You will handle it badly at first",
            "Horoscope: Midweek opportunity | Arrives on a day you took off",
            "Horoscope: Finances: steady | Which is another word for static",
            "Horoscope: Unexpected news | From someone you had forgotten",
            "Horoscope: This week: reflect | On whether you replied to that email",
            "Horoscope: Travel indicated | Probably just the commute though",
            "Horoscope: A decision looms | You already know the answer",
            "Horoscope: Energy levels low | Stars suggest: an early night",
            "Horoscope: Creative week ahead | Whether you want one or not",
            "Horoscope: Social occasion due | Prepare an excuse just in case",
            "Horoscope: Mercury in something | Apparently this matters now",
            "Horoscope: Minor setback due | Specifically before Wednesday",
            "Horoscope: Reconnect this week | Someone you owe a reply to",
            "Horoscope: Home improvements | Stars: the dripping tap, specifically",
            "Horoscope: Week of contrasts | Some good, some not, much the same",
            "Horoscope: Patience rewarded | Eventually, stars are vague on when",
            "Horoscope: Thursday is key | Stars decline to say why exactly",
            "Horoscope: Ambitions are good | Lower them slightly this week though",
            "Horoscope: Luck is nearby | Stars suggest: check your coat pocket",
            // ── Local ─────────────────────────────────────────────────────
            "Local: Planning row escalates | Third meeting, same argument",
            "Local: Community garden opens | Plot two already disputed",
            "Local: Road closed all week | Diversion: adds twenty minutes",
            "Local: Clock tower repairs due | Clock to remain wrong throughout",
            "Local: Library book sale on | Same books as last year, mostly",
            "Local: Council votes postponed | Venue double-booked, again",
            "Local: New mural proposed | Location: already controversial",
            "Local: Memorial bench installed | Plaque unreadable in direct sun",
            "Local: Litter pick this Sunday | Weather permitting, which it won't",
            "Local: Allotment waiting list | Currently: four years minimum",
            "Local: Park café reopens | Under new management, same sandwiches",
            "Local: Annual fair returns | Slightly smaller than last year",
            "Local: Speed camera installed | Already disputed by three drivers",
            "Local: New bins arrive | Wrong size, wrong colour, still bins",
            "Local: Community hall to close | Temporarily, say the council carefully",
            "Local: River walk reopened | Partially, say signs every fifty metres",
            "Local: Town twinning vote | Nobody remembers the last twin",
            "Local: Bonfire night moved | To a date with worse weather",
            "Local: Recycling changes again | Blue box, green box, still confused",
            "Local: Market stalls reduced | Four left, all selling candles",
            // ── Celebrity ─────────────────────────────────────────────────
            "Celebrity: Brenda Cole moves house | Previous house: also in the news",
            "Celebrity: Gary Voss takes holiday | Show: noticeably worse without him",
            "Celebrity: Tasha Quill launches app | Does one thing, slowly",
            "Celebrity: Dean Mercer writes column | About knees, mostly knees",
            "Celebrity: Pixie Lark goes camping | Tent: branded, experience: curated",
            "Celebrity: Brenda Cole in talks | For what: unclear, confirmed: nothing",
            "Celebrity: Gary Voss gets a dog | Dog: immediately more popular",
            "Celebrity: Tasha Quill at the gym | Different gym, same tripod",
            "Celebrity: Dean Mercer: comeback? | Knees: consulted, answer: pending",
            "Celebrity: Pixie Lark: no filter | Filter: present, just a subtle one",
            "Celebrity: Brenda Cole: statement | Clarifies nothing, raises questions",
            "Celebrity: Gary Voss: new segment | Listeners: divided on the segment",
            "Celebrity: Tasha Quill: collab | With someone slightly more famous",
            "Celebrity: Dean Mercer guest spot | On Gary Voss's show, went long",
            "Celebrity: Pixie Lark: book deal | Chapter one: already controversial",
            "Celebrity: Brenda Cole: spotted | At an event she said she skipped",
            "Celebrity: Gary Voss: feud denied | With who: he will not confirm",
            "Celebrity: Tasha Quill: new look | Described as: a choice",
            "Celebrity: Dean Mercer masterclass | Attendees: unsure what they learned",
            "Celebrity: Pixie Lark: offline? | Posted seventeen times since saying so",
            // ── Business ──────────────────────────────────────────────────
            "Business: New café opens downtown | Third this year, second this block",
            "Business: Hardware shop rebrands | Name: longer, logo: smaller",
            "Business: Florist expands | Into cards, then candles, then everything",
            "Business: Restaurant review mixed | Food fine, chair uncomfortable",
            "Business: Corner shop changes hands | Prices: up, selection: same",
            "Business: Gym membership offer | Free month, then quietly not free",
            "Business: Bookshop hosts event | Attendance: better than expected",
            "Business: Bakery new menu item | Unpronounceable, sells out daily",
            "Business: Market stall goes permanent | Former stall: now a shop",
            "Business: Estate agent opens | Fifth one on the high street now",
            "Business: Nail bar expansion | Into the space the estate agent left",
            "Business: Pub revamp done | Same pub, different uncomfortable stools",
            "Business: Takeaway: new owner | Same menu, different bags",
            "Business: Office space available | Above the old travel agent",
            "Business: Photography studio opens | First client: a dog, apparently",
            "Business: Deli: closing early | Citing: not enough people at 7am",
            "Business: Laundrette under new name | Machines: same, branding: bolder",
            "Business: Optician expanding | Into the space nobody can identify",
            "Business: Record shop returns | Vinyl only, card machine: optional",
            "Business: Flower kiosk outside station | Already beloved, already in the way",
            // ── Sport ─────────────────────────────────────────────────────
            "Sport: Dean Mercer charity run | Completed, slowly, with dignity",
            "Sport: Local five-a-side league | Table: disputed since matchday two",
            "Sport: Swimming gala results | Times: recorded, medals: not enough",
            "Sport: Junior football tournament | Three red cards, all adults",
            "Sport: Cycle race through town | Road closed, nobody told the buses",
            "Sport: Bowls club: annual final | Disputed on technical grounds, resolved",
            "Sport: Dean Mercer: exhibition match | Knees held. Just.",
            "Sport: Park run record broken | Previous record: also disputed",
            "Sport: Darts league: semi-final | Venue: the pub, as always",
            "Sport: School sports day results | Weather held, mostly",
            "Sport: Tennis club membership full | Waiting list: two years minimum",
            "Sport: Charity golf day | Scores: not disclosed, weather: fine",
            "Sport: Rowing club: new boat | Old boat: not discussed",
            "Sport: Local boxing show | Four bouts, one controversy",
            "Sport: Dean Mercer opens new track | Cut ribbon, left, did not run",
            "Sport: Angling competition: result | Winner: quiet about it, politely",
            "Sport: Martial arts club moves | To the community hall, temporarily",
            "Sport: Cricket season starts | Rain: immediately, as tradition demands",
            "Sport: Basketball hoop installed | Already bent, cause: disputed",
            "Sport: Triathlon: local entries | Twelve entered, nine finished, all tired",
            // ── Deals ─────────────────────────────────────────────────────
            "Deals: {restaurant} | Two courses, Tue to Thu only",
            "Deals: Dry cleaning deal | First visit, terms apply",
            "Deals: Cinema: Tuesday | Excludes new releases",
            "Deals: {hardware} | Free delivery, orders over £30",
            "Deals: {cafe} | Loyalty card: tenth free",
            "Deals: Car wash: half price | Monday only, before 10am",
            "Deals: {restaurant} | Early bird menu on now",
            "Deals: {gym} | January offer, runs to March",
            "Deals: Bakery: day-old | Still good, deeply discounted",
            "Deals: Flowers: this week | Seasonal, while stocks last",
            "Deals: Free parking Sundays | Bays limited, popular day",
            "Deals: {restaurant} | Pizza: third month running",
            "Deals: Phone repair: today | Terms apply, parts permitting",
            "Deals: {shop} | Multi-buy, on usual items",
            "Deals: {deli} | End of day sale from 4pm",
            "Deals: Bookshop: clearance | Eclectic, charitable pricing",
            "Deals: Pub: quiz night | Drink deal with entry, Wed",
            "Deals: Optician: eye test | Free with purchase",
            "Deals: Print shop: bulk | Ten or more, call ahead",
            "Deals: Market: cash only | Card machine: resting",
            "Deals: {gym} | Off-peak membership available",
            "Deals: {cafe} | New loyalty scheme this month",
            "Deals: {restaurant} | Set menu: two courses",
            "Deals: {salon} | Group bookings: three or more",
            "Deals: {hardware} | Weekend workshop, free entry",
            "Deals: {deli} | Tasting afternoon, Saturday only",
            "Deals: {cafe} | Student discount, ID required",
            "Deals: {gym} | Bring a friend: one free visit",
            "Deals: {restaurant} | Kids eat free, weekdays",
            "Deals: {salon} | Colour deal, book this week",
            "Deals: {hardware} | Free fitting on selected items",
            "Deals: {deli} | Cheese of the month available",
            "Deals: Pub: two for one | Sunday lunch, book ahead",
            "Deals: {cafe} | Takeaway: 10p off, own cup",
            "Deals: {gym} | Free trial week, no commitment",
            "Deals: {restaurant} | Birthday: free dessert",
            "Deals: {salon} | Referral reward: both save",
            "Deals: {hardware} | Trade discount, Mondays only",
            "Deals: {deli} | Lunch box, built to order",
            "Deals: {cafe} | Afternoon tea from 2pm",
        };

        // ── Filler pool ───────────────────────────────────────────────────
        // Placeholders: {company} → DoMakeCompanyName() (corporate/investment-firm-flavoured)
        public static readonly string[] FillerPool = {
            // ── Weather ───────────────────────────────────────────────────
            "Today's forecast: partly cloudy, high of 18°C. Light rain expected tomorrow.",
            "Today's forecast: overcast with a chance of municipal meetings running long.",
            "Today's forecast: bright and breezy, with a strong chance of someone's hat ending up in the river.",
            "Weather: fog rolling in this evening. Visibility poor, excuses for being late to council meetings excellent.",
            "Today's forecast: clear skies, ideal conditions for pretending to enjoy a picnic.",
            "Weather: thunderstorms expected overnight. The pigeons have already left.",
            "Today's forecast: unseasonably warm. Several residents seen wearing shorts unwisely early.",
            "Weather: light drizzle most of the day, heavy drizzle if you forgot your umbrella.",
            "Today's forecast: windy enough to rearrange three gardens and one councillor's toupee.",
            "Today's forecast: scattered showers, scattered opinions on whether an umbrella was really necessary.",
            "Weather: heavy snow expected. The salt trucks are, as ever, optimistic about their chances.",
            "Today's forecast: humid, with visibility reduced by everyone's car windows fogging up at once.",
            "Weather: a brief but dramatic hailstorm passed through, startling three pigeons and one councillor.",
            "Today's forecast: sunny with a high chance of someone complaining it's too sunny.",
            "Weather: cold front moving in. Residents advised to locate their second-best coat.",
            "Today's forecast: patchy fog this morning, patchy attendance at the early council session.",
            "Weather: a rare double rainbow spotted over the industrial estate. Nobody nearby to appreciate it properly.",
            "Today's forecast: mild with light winds, perfect conditions for a kite to escape forever.",
            "Weather: first frost of the season. Gardeners observed staring mournfully at tomato plants.",
            "Today's forecast: variable cloud, variable mood, residents advised to just bring a coat anyway.",
            // ── Quirky Local News ─────────────────────────────────────────
            "Cat rescued from town hall clock tower for third time this year.",
            "Local man's prize-winning tomatoes stolen from allotment, police baffled.",
            "Local woman's garden gnome collection now visible from space, neighbours report.",
            "Mystery accordion music heard nightly near the old mill. No accordion, or musician, ever found.",
            "Local dog elected honorary deputy mayor by unanimous vote of the dog. No objections raised.",
            "Town square pigeon population now believed to outnumber actual residents. Census disputed.",
            "Resident's hedge, trimmed into shape of former mayor, quietly removed overnight. No comment given.",
            "Annual duck race postponed after lead duck reportedly demanded better terms.",
            "Local bakery's bread sculpture of the town hall mistaken for actual town hall by lost tourist.",
            "Man who has complained about the streetlights since 2019 finally invited to switch them on himself.",
            "Town's oldest resident reveals secret to longevity is \"ignoring the council newsletter entirely.\"",
            "Local man's homemade weather vane mysteriously always points toward the pub.",
            "Annual scarecrow festival marred by scarecrow winning best-dressed at unrelated wedding.",
            "Resident's koi pond fish reportedly recognised and greeted by name. Fish unavailable for comment.",
            "Town's \"Wall of Fame\" mural quietly repainted after someone added a moustache to the mayor.",
            "Local allotment dispute over a single courgette enters its third month, neighbours exhausted.",
            "Stray cat adopts town hall as residence, promptly promoted to \"unofficial morale officer.\"",
            "Mysterious crop circle in farmer's field identified as tractor doing a three-point turn.",
            "Town's \"Spot the Difference\" community noticeboard accidentally became genuinely difficult puzzle.",
            "Local man's garden shed wins regional \"Most Improved Structure\" award nobody knew existed.",
            // ── Letters to the Editor ─────────────────────────────────────
            "Letters: why are the pigeons in the park getting bigger? - concerned resident.",
            "Letters: the new bus schedule is either brilliant or a personal attack, residents undecided.",
            "Letters: can someone please tell the seagulls it's not their bin.",
            "Letters: is it just me, or has the duck pond gotten suspiciously deeper? - worried swimmer.",
            "Letters: whoever keeps moving the bins back, please stop, this is escalating. - tired of it.",
            "Letters: the new park bench is lovely but faces directly into the sun. Who approved this? - squinting.",
            "Letters: I have counted the streetlights three times and the number keeps changing. - concerned.",
            "Letters: in defence of the seagulls, they were here first. - devil's advocate.",
            "Letters: can the council confirm whether the town hall clock has ever told the correct time. - curious.",
            "Letters: my neighbour's wind chimes are a human rights issue at this point. - sleepless.",
            "Letters: the new road markings appear to lead directly into a hedge. Asking for a friend.",
            "Letters: why does the town hall clock chime thirteen times at noon. Genuinely asking.",
            "Letters: in support of the seagulls, actually - they've never once let me down. - contrarian.",
            "Letters: someone has been leaving notes on my car about my parking. I live here. - defensive.",
            "Letters: the new bench by the river is wonderful, who do I thank. - grateful.",
            "Letters: has anyone else noticed the duck pond ducks judging us. - paranoid, possibly correct.",
            "Letters: the bins were collected on the wrong day again. This is becoming personal. - frustrated.",
            "Letters: I would like to formally nominate the town's worst-parked car for an award. - petty, but fair.",
            "Letters: the new flowerbeds are beautiful, but who keeps stealing the tulips. - heartbroken gardener.",
            "Letters: can we talk about how loud the church bells are on a Sunday morning. - not a morning person.",
            // ── Horoscope ─────────────────────────────────────────────────
            "Your stars this week: a new opportunity may present itself. Beware strangers bearing spreadsheets.",
            "Horoscope: today is a good day to avoid eye contact with the swans.",
            "Horoscope: the stars suggest patience this week, especially at the permit office.",
            "Horoscope: this week favours bold decisions, except regarding parking. Never regarding parking.",
            "Horoscope: a long-lost item will resurface. It is probably under the sofa.",
            "Horoscope: avoid arguments with seagulls this week. You will not win.",
            "Horoscope: the stars are unusually quiet on the subject of bin collection day.",
            "Horoscope: an unexpected visitor may arrive. Recommend tidying at least one room.",
            "Horoscope: a minor inconvenience today will become an excellent story by Friday.",
            "Horoscope: this is a good week to finally read that one notice board nobody reads.",
            "Horoscope: today favours quiet reflection, ideally somewhere the pigeons can't find you.",
            "Horoscope: a minor disagreement with a vending machine is foretold. You will lose.",
            "Horoscope: the stars suggest this is not the week to trust the weather forecast.",
            "Horoscope: an old friend may reach out. Reply promptly, or face mild guilt for weeks.",
            "Horoscope: today is ideal for starting a project you will abandon by Thursday.",
            "Horoscope: the universe encourages you to finally fix that one wobbly table leg.",
            "Horoscope: a sudden urge to reorganise a drawer will strike without warning. Embrace it.",
            "Horoscope: this week, the stars are mostly concerned with whether you've eaten enough vegetables.",
            "Horoscope: an unexpected compliment is coming. Try not to look as surprised as you feel.",
            "Horoscope: today is not the day to make eye contact with the office printer.",
            // ── Celebrity News ────────────────────────────────────────────
            // Recurring cast: Brenda Cole (soap), Gary Voss (radio DJ),
            // Tasha Quill (reality TV), Dean Mercer (ex-athlete), Pixie Lark (influencer)
            "Soap star Brenda Cole spotted buying suspiciously many lottery tickets at the corner shop again.",
            "Local radio DJ Gary Voss denies rumours he's \"lost his voice for dramatic effect,\" sources unconvinced.",
            "Reality TV's Tasha Quill seen arguing with a parking meter, loses, files complaint anyway.",
            "Former athlete Dean Mercer's comeback tour postponed after disagreement with own knees.",
            "Influencer Pixie Lark's \"authentic small-town lifestyle\" video filmed entirely in a borrowed kitchen.",
            "Brenda Cole's memoir delayed for the third time. Publisher reportedly \"still waiting for an ending.\"",
            "Gary Voss spotted wearing sunglasses indoors, refuses to confirm or deny recent eye exam.",
            "Tasha Quill's new fitness brand under fire after treadmill incident caught on neighbour's doorbell camera.",
            "Dean Mercer seen jogging at 6am again, neighbours unsure if it's training or fleeing something.",
            "Pixie Lark's \"decluttering journey\" video filmed in a house with three visible storage units rented nearby.",
            "Brenda Cole denies feud with Gary Voss, immediately starts feud with Gary Voss live on his show.",
            "Local sources confirm Tasha Quill's \"spontaneous\" café visit involved four assistants and a tripod.",
            "Dean Mercer's autobiography reportedly two-thirds acknowledgements, one-third actual content.",
            "Gary Voss's late-night show ratings climb after he accidentally left his microphone on during an argument with his cat.",
            "Pixie Lark spotted at the farmers' market, immediately asks if the vegetables are \"camera-ready.\"",
            "Brenda Cole's new perfume, \"Bren,\" described by critics as \"assertive\" and \"hard to leave a room after.\"",
            "Tasha Quill announces she's \"taking a break from public life,\" posts about it eleven times that day.",
            "Dean Mercer's testimonial for the new gym quietly removed after gym owner clarified he'd never actually joined.",
            "Gary Voss claims he \"predicted the weather better than the forecast\" once, in 2011, never lets it go.",
            "Pixie Lark's tell-all interview reveals shockingly little, runs forty-five minutes anyway.",
            // ── Business News (corporate/investment/mergers/shares) ─────────
            "{company} shares climb 4% after announcing \"strategic realignment,\" details to follow, eventually.",
            "{company} completes merger with rival firm, name of combined entity still being argued over internally.",
            "{company}'s quarterly earnings call described by analysts as \"long,\" \"vague,\" and \"ultimately fine.\"",
            "{company} announces layoffs alongside record profits, citing \"efficiency,\" declines further comment.",
            "{company} acquires smaller competitor for an \"undisclosed sum,\" widely assumed to be a lot.",
            "{company}'s stock dipped briefly today after CEO's interview went, in the words of one trader, \"oddly philosophical.\"",
            "{company} shareholders approve executive bonus package despite year of flat growth, citing \"long-term vision.\"",
            "{company} confirms it is \"exploring strategic options,\" market interprets this as either very good or very bad news.",
            "{company}'s new CFO promises \"renewed focus on fundamentals,\" market reaction muted but polite.",
            "{company} share price unaffected by scandal, analysts baffled, shareholders relieved.",
            "{company} announces it will relocate its headquarters, again, for the third time this decade.",
            "{company} reports \"modest growth,\" which several analysts note is corporate for \"no growth.\"",
            "{company}'s board approves merger talks with a firm nobody had previously heard of.",
            "{company} issues statement clarifying it is \"not for sale,\" fuelling immediate speculation it is for sale.",
            "{company} shares surge after rumour of takeover bid, surge reverses after rumour is denied.",
            "{company} announces a \"comprehensive restructuring,\" internal memo reportedly just says \"wait and see.\"",
            "{company}'s annual shareholder meeting runs four hours over schedule, resolves nothing of substance.",
            "{company} confirms talks with investors are \"ongoing and constructive,\" which satisfies absolutely nobody.",
            "{company}'s new five-year plan unveiled to muted applause and one audible sigh.",
            "{company} shares hold steady despite CEO's resignation, market apparently unsurprised either way.",
        };

        // ── Beefy filler: longer stories for Herald / Civic Pulse "Around Town" section ──
        public static readonly string[] BeefyFillerPool = {
            // ── Local & civic ────────────────────────────────────────────────────────────
            "The town's oldest pedestrian crossing has finally been repainted after a two-year campaign by a single resident who sent a letter every fortnight without fail. The council has confirmed the letters were appreciated, though insists the timing is a coincidence.",
            "Plans to install a new clock tower in the civic square have been quietly shelved following disagreement over which direction it should face. A sub-committee has been formed. It has already met twice and agreed on very little.",
            "The municipal swimming pool will close for renovations starting next month, with works expected to take six weeks. Local sources suggest this figure has historically been treated as an opening offer.",
            "A proposal to rename the high street in honour of a local figure has sparked unexpected debate, with twelve names suggested, nine of them the same person's own relatives. A public vote is expected before the end of the financial year.",
            "The town's community orchard, planted by volunteers three years ago, has produced its first meaningful harvest. Residents are invited to pick their own fruit on weekends, though the sign explaining this has reportedly been stolen.",
            "Parking permit fees are set to rise for the second year in a row, a move the council describes as 'modest and necessary.' Residents queuing to renew permits described it using different words.",
            "The new cycle lane on Market Street has divided opinion sharply, with cyclists calling it overdue and drivers calling it several other things. A review is planned for spring.",
            "An application to list the town's newest leisure centre as a building of architectural interest has been submitted, surprising everyone including the person who submitted it.",
            "Resurfacing works on the bridge approach road are complete, three months behind schedule and slightly over budget. The council has called the result 'excellent' and 'worth the wait.' One local described it as 'just a road.'",
            "The council's new online portal for reporting issues launched to moderate enthusiasm and immediate technical difficulties. A helpline was set up to assist residents. The helpline's number was listed incorrectly on the website.",
            // ── Community & culture ──────────────────────────────────────────────────────
            "The town's annual autumn fair is expected to draw record numbers this year following last year's surprise popularity of the competitive jam section. Entries for the preserve category are already being received, with judges described as 'prepared but cautious.'",
            "A local history group has completed a two-year oral history project, gathering interviews from over eighty long-term residents. The archive will be donated to the library, where it will be available to borrow alongside the usual selection of large-print thrillers.",
            "The town choir's end-of-year concert sold out in under four hours, a fact that surprised the choir, their families, and apparently the booking website, which crashed twice.",
            "A community mural planned for the side of the old post office has received planning approval. The design, chosen by public vote, beat out a proposed second design by a margin of seven votes, which the second design's creator is still processing.",
            "The local amateur dramatics society's production of a classic play opens next Thursday. The director has described it as 'a fresh interpretation.' Cast members have described it as 'not what any of us expected, but we're committed now.'",
            "The town museum's new exhibition on local industry opens to the public this weekend. Entry is free, though the gift shop is described by staff as 'very well-stocked' and 'strategically placed.'",
            "A petition to restore the town's Victorian bandstand has gathered over eight hundred signatures in less than a week. The council has acknowledged the petition and confirmed it will be reviewed 'in due course,' a phrase residents have learned to interpret cautiously.",
            // ── Quirky extended ──────────────────────────────────────────────────────────
            "The duck pond on Elmfield Green has been temporarily drained for maintenance, leaving its resident ducks confused and increasingly opinionated about it. Temporary accommodation has been arranged. The ducks are reportedly unimpressed.",
            "A local man who has maintained the same allotment plot for thirty-one years has finally entered the produce competition he has been quietly preparing for since 1997. He came second. He is already preparing for next year.",
            "The town's unofficial 'most politely contested parking space' has passed to a new claimant following the retirement of the previous holder, who spent six years defending a spot on Cedar Road without once raising his voice.",
            "Three separate residents have independently applied to adopt the stray cat that has been living outside the library for the past year. The cat has reviewed all three applications and declined each one on its own schedule.",
            "The new seating outside the market hall has proved so popular that a second row of chairs is being considered. The original benches were installed following a campaign that took four years. Residents are cautiously optimistic about the timeline.",
            // ── Celebrity news ───────────────────────────────────────────────────────────
            // One-off figures prioritised; running cast (Brenda/Gary/Tasha/Dean/Pixie) used sparingly and only consistently with their established stories
            "Award-winning chef Marco Bellini has announced the closure of his third restaurant this year, blaming 'an unworkable relationship with the current dining public.' A memoir is said to be in preparation. His publicist has confirmed only that it will be 'very candid.'",
            "Retired television presenter Sandra Holt has re-emerged after a three-year absence to launch a podcast about silence. The first episode runs forty minutes and contains no speaking. It has received mixed but fascinated reviews.",
            "Actor turned wellness entrepreneur Callum Reece is facing questions after his new health supplement was found to contain, in the words of one analyst, 'mostly optimism.' Legal representatives have called the findings 'preliminary and frankly hurtful.'",
            "Former pop duo Sunset Twin have announced a reunion tour, seventeen years after their acrimonious split. Both members have confirmed they are 'genuinely excited' and 'professionally cordial.' Ticket sales are described as brisk.",
            "Fashion designer Orla Vane's new collection, shown at last week's regional showcase, has divided critics. Half called it 'a bold reimagining of utility wear.' The other half called it 'a lot of pockets.' Both sides appear correct.",
            "Sports commentator Neil Farrow has been quietly dropped from his broadcaster's roster after a live broadcast in which he described a goalless draw as 'poetic.' Colleagues have declined to comment. His agent says he stands by it.",
            "Celebrity gardener Fern Oakley's new television series has been delayed following a dispute over 'creative direction.' Oakley has confirmed she wanted more composting. The production company wanted less. No resolution has been reached.",
            "Chart-topping singer Ria Solano was spotted this week moving into a property in the region, which local estate agents are already describing as 'a significant vote of confidence in the area.' Solano has not confirmed the purchase or commented on the area's confidence.",
            "Former reality contestant Marcus Webb has pivoted to motivational speaking, booking out a local hotel conference room for his debut event. Forty-three people attended. Webb has called it 'an intimate masterclass.' Attendees were divided on the masterclass element.",
            "Novelist Petra Haines has confirmed that her long-awaited follow-up to her debut will be released 'when it is ready,' a position she has maintained consistently for six years and which her publisher appears to have accepted.",
            "Television chef Dominic Farley has launched a range of premium tinned goods, describing them as 'the future of fine dining.' Food critics have been divided, with responses ranging from 'genuinely interesting' to 'a tin of soup with a ribbon on it.'",
            "Retired footballer Leon Birch has opened a café in the town centre, his second business venture following the closure of his sports bar in 2022. The café is described as 'relaxed and unpretentious.' The prices have been described as neither.",
            "Author and television personality Kit Morrow has announced she is writing a children's book, her first, after seventeen years of adult fiction. Her publisher has called it 'a natural evolution.' Morrow has called it 'surprisingly difficult to write without swearing.'",
            "Jazz musician Theo Anand has returned from a two-year residency abroad to find his fanbase has both grown and aged considerably. A homecoming concert is scheduled for next month. Tickets are available and described as 'affordable, finally.'",
            "Actor Simone Dacre has confirmed she will not be returning for the fourth series of the drama that made her famous, citing 'creative fulfillment' and 'a character who has quite literally nowhere left to go.' The show will continue without her.",
            "Fitness influencer and former gymnast Cara Weston has launched a subscription app promising 'results in twelve minutes a day.' Consumer watchdogs have noted the disclaimer at the bottom of the promotional material is longer than the workout.",
            "Interior designer to the minor-celebrity set, Hugo Strand, has published his second book on maximalist décor. Early reviews note it contains even more fringe than the first, in both content and physical trim.",
            "Comedian Roz Nketiah's new stand-up special, filmed at a regional theatre, has been picked up by a streaming platform following a bidding process described as 'brief but spirited.' Nketiah says she is 'thrilled and mildly suspicious.'",
            "Sportswear brand co-founded by former sprinter Yemi Adisa has secured a distribution deal with a major retailer, five years after launching from a spare bedroom. Adisa has said the journey taught her patience. The spare bedroom has since been converted into a home office.",
            "Travel presenter Luca Vane has announced a new series visiting places 'tourists never go.' Early filming reports suggest at least two of the locations have since opened tourist offices in response to the show's production crew arriving.",
            "Classical pianist Ingrid Sol has cancelled the remaining dates of her current tour, citing exhaustion. Her management has confirmed she is resting. Industry contacts note she has been photographed at three separate award ceremonies since the announcement.",
            "True crime podcaster Dan Hulme has expanded into television with a documentary series described as 'responsible and considered.' Viewers have described it as 'quieter than expected.' Hulme considers this a compliment.",
            "Former child actor turned property developer Elliot Chance has sold his renovated farmhouse for a reported sum well above asking price, the third such sale in four years. Chance credits 'an eye for potential.' Estate agents credit 'good timing and a very photogenic kitchen.'",
            "Lifestyle brand founder Aoife Brennan has stepped back from day-to-day operations of her company following a period she describes as 'necessary reflection.' The company has confirmed operations continue as normal. Staff have confirmed they noticed very little difference.",
            "Award-nominated documentary filmmaker Priya Sethi has announced her next project will examine the lives of people who actively avoid being documented. Funding has been secured. The subjects, by definition, have not yet been confirmed.",
            // ── Financial news ───────────────────────────────────────────────────────────
            "{company} has reported its strongest quarterly results in a decade, crediting a return to 'straightforward banking' and 'not doing anything especially clever.' Analysts have described the strategy as unexpectedly effective.",
            "{company} has submitted plans for a mixed-use development on the old industrial site east of the town centre. The proposal includes residential units, retail space, and what the planning documents describe as a 'contemplation garden,' details of which remain vague.",
            "{company} has announced the expansion of its regional depot, adding an estimated two hundred jobs over the next eighteen months. The company credited 'sustained local demand' and 'a warehouse that finally has enough car parking.'",
            "{company} has quietly acquired a majority stake in three local commercial properties, according to records filed this week. The fund has offered no comment. A spokesperson confirmed the fund exists.",
            "{company} has announced the closure of two underperforming branches, including one in the high street that had been trading for over thirty years. A leaving sale is planned. Staff have been offered positions at other sites, with varying degrees of enthusiasm reported.",
            "{company} has relocated its regional headquarters to a new office park on the outskirts of town, citing 'collaborative workspace design' and 'significantly cheaper rent.' The rent point was added in a follow-up statement after the first was queried.",
            "{company} has confirmed plans to convert the old Granary building into a boutique hotel, subject to planning approval. The project, estimated at twelve million, is expected to take two years. Industry observers note this estimate has been described as 'ambitious but earnest.'",
            "{company} has lodged a planning application for a new store on the retail park by the bypass, its third attempt to establish a presence in the area. Previous applications were refused on traffic grounds. This one includes a revised traffic assessment and, notably, more parking.",
        };

        // ── Winner victory quotes — used in Herald sidebar pull quote ─────────────────
        public static readonly string[] WinnerQuotePool = {
            "The people have spoken, and I will not let them down. - {winner}",
            "This is not my victory. It belongs to every resident who believed change was possible. - {winner}",
            "I came into this race with one promise: to listen. That starts tomorrow. - {winner}",
            "We ran a clean campaign on real issues. I hope that still counts for something. - {winner}",
            "This city deserves better, and together we are going to deliver it. - {winner}",
            "I am humbled by the trust placed in me tonight. It is a responsibility I take seriously. - {winner}",
            "The mandate is clear. Now the work begins. - {winner}",
            "To those who voted for me and those who did not - I will be mayor for all of you. - {winner}",
            "We did not win tonight by accident. We won because people are ready for change. - {winner}",
            "I have no interest in the title. I am interested in the results. - {winner}",
        };
    }
}

